### ISSUE TITLE
Fix tooltips

### ISSUE THREAD

**Issue by monkeyscript** [monkeyscript/monkey-charts#1]
There are commented code for showing tooltip for every chart. 

For example, line 100 in _projects/monkey-charts/src/lib/components/horizontal-bar/horizontal-bar.component.ts_ : 
```
tooltip.style("left", d3.event.x + "px")
           .style("top", d3.event.y + "px")
           .style("display", "inline-block")
           .html(tooltipText);
```

Right now the tooltip positions are determined by D3 events. This causes the tooltips to go span away from the chart and may go beyond viewport too. There are two possible solutions,

1. The tooltip positions should be relative to the chart container (recommended).
2. If the tooltip position goes beyond the chart container, relocate in such a way that it fits inside the container.

Prefer people with experience in D3.js and Angular package development.

**Comment by MykolaKolotylo** [comment]
Hello @monkeyscript. Can I take this issue?

**Comment by monkeyscript** [comment]
Sure @MykolaKolotylo. Just make sure you test with multiple instances of the same chart (with different chart ID and data).

**Comment by MykolaKolotylo** [comment]
@monkeyscript sent a PR, please take a look

**Comment by monkeyscript** [comment]
@MykolaKolotylo Please try with multiple instances of the same chart.

**Comment by MykolaKolotylo** [comment]
oh, ok will try

**Comment by MykolaKolotylo** [comment]
hey @monkeyscript could you please take a look again https://github.com/monkeyscript/monkey-charts/pull/3
